# Site settings
title: Leonardo Moura
email: leofsmoura@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Leonardo Moura is a developer, writer, and artist.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://leomoura.org" # the base hostname & protocol for your site
twitter_username: lfsmoura
github_username:  lfsmoura

# Build settings
encoding: utf-8
highlighter: rouge
markdown: kramdown

sitemap:
  file: "/sitemap.xml"
  exclude:
      - "/atom.xml"
      - "/feed.xml"
      - "/feed/index.xml"
  include_posts:
      - "/index.html"
  change_frequency_name: "change_frequency"
  priority_name: "priority"

#menu
pages_list:
  Blog: '/blog/'
  Livros: '/livros/'
#  Sobre: '/about/'
  Trabalhos: '/trabalhos/'
  Videos: '/videos'
