# Site settings
title: Leonardo Moura
email: leofsmoura@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Leonardo Moura is a developer, writer, and artist.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://lfsmoura.github.io" # the base hostname & protocol for your site
twitter_username: lfsmoura
github_username:  lfsmoura

# Build settings
markdown: redcarpet

encoding: utf-8
highlighter: pygments

#menu
pages_list:       
  Blog: '/blog/'
  Sobre: '/about/'
  Trabalhos: '/trabalhos/'
  Lattes: http://lattes.cnpq.br/3495887322246706
#  Consultoria: '/consultoria'
