version: '2'
services: 
  jekyll:
    image: "jekyll/jekyll"
    command: jekyll s --host 0.0.0.0 --force_polling
    volumes:
        - .:/srv/jekyll
        - ./vendor/bundle:/usr/local/bundle
    ports:
      - "4000:4000"
    expose:
      - "4000"
