name: Sync Notion
run-name: ${{ github.actor }} is syncing Notion
on:
  schedule:
    - cron: "*/10 * * * *"
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Clean up notes
        run: rm -rf notes/*

      - name: Notion Sync
        run: npm run notion-sync
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}

      - name: List notes in the repository
        run: |
          ls ${{ github.workspace }}/notes

      - name: Check for changes
        id: changes
        run: |
          git diff --quiet || echo "::set-output name=changes::true"
          git diff --cached --quiet || echo "::set-output name=changes::true"
        shell: bash

      - name: Commit files
        if: steps.changes.outputs.changes == 'true'
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -a -m "Sync Notes"

      - name: Push changes
        if: steps.changes.outputs.changes == 'true'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
